### PR TITLE
I15-1 beamline testing

### PR DESCRIPTION
**Pull request by mtwharmby**
Bug fixes to ScanAtomProcess and QueueListener which now allow ScanAtoms to be processed by the QueueService. Also adds significant amounts of debug logging to the QueueService and some of the processors.

@Mark-Booth - the contents of this pull-request are needed for testing on Monday, so can they be rolled into your testing version of GDA for the beamline at least please?

Fixes for tickets: I15_1-355, I15_1-359, I15_1-386
Partial work for: I15_1-384, I15_1-387, I15_388,

### CODE REVIEW

**Comment by mtwharmby** [comment]
I've restarted the travis tests on this twice due to failures not related to what I'm committing (first was to do with Benchmarking 1 point taking longer than 100ms; second time the consumers just fell over and stopped responding to the tests).
@gerring Has the test suite become a bit sensitive again?

**Comment by Mark-Booth** [comment]
Tests are passing now, these all look like reasonable changes and none of these changes look like they would affect any beamline other than I15-1, so I'm happy to merge these commits.

**Comment by Mark-Booth** [comment]
After pulling, I noticed a commit missing from your pull request, but it only adds a commented out line of code and a FIXME comment, so I guess it's not a problem for these lines to be missing.

**Comment by mtwharmby** [comment]
Can you let me know the commit signature please, just so I know which one it is. Thanks!

Michael

**Comment by Mark-Booth** [comment]
I was referring to 72ad28d : https://github.com/mtwharmby/scanning/commit/72ad28d69f4d6aa87a4f8dd738a18a1661c46f6b

**Pull request merged**
