### PR TITLE
I15_1 (9.3pre) Rename queues.spooler plugin to queuesspooler

### PR DESCRIPTION
**Pull request by Mark-Booth**
Since org.eclipse.scanning.event.queues is defined in another plugin,
org.eclipse.scanning.event.queues.spooler.ServicesHolder cannot be found
in Jython. Moving it into it's own packaged fixes this problem.

### CODE REVIEW

**Comment by gerring** [comment]
SonarQube analysis reported 28 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 10 minor
* ![INFO][INFO] 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [QueueBeanFactory.java#L153](https://github.com/eclipse/scanning/blob/1cc2b60843771f99282cc9bc1e44a19815315c37/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/QueueBeanFactory.java#L153): Define a constant instead of duplicating this literal " found in registry." 4 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ServicesHolder.java#L28](https://github.com/eclipse/scanning/blob/1cc2b60843771f99282cc9bc1e44a19815315c37/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/ServicesHolder.java#L28): Make the enclosing method "static" or remove this set. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2696)
1. ![CRITICAL][CRITICAL] [ServicesHolder.java#L29](https://github.com/eclipse/scanning/blob/1cc2b60843771f99282cc9bc1e44a19815315c37/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/ServicesHolder.java#L29): Make the enclosing method "static" or remove this set. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2696)
1. ![CRITICAL][CRITICAL] [ServicesHolder.java#L33](https://github.com/eclipse/scanning/blob/1cc2b60843771f99282cc9bc1e44a19815315c37/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/ServicesHolder.java#L33): Make the enclosing method "static" or remove this set. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2696)
1. ![CRITICAL][CRITICAL] [IBeanAssembler.java#L44](https://github.com/eclipse/scanning/blob/1cc2b60843771f99282cc9bc1e44a19815315c37/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/IBeanAssembler.java#L44): Remove usage of generic wildcard type. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [IBeanAssembler.java#L55](https://github.com/eclipse/scanning/blob/1cc2b60843771f99282cc9bc1e44a19815315c37/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/IBeanAssembler.java#L55): Remove usage of generic wildcard type. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [PositionerAtomAssembler.java#L34](https://github.com/eclipse/scanning/blob/1cc2b60843771f99282cc9bc1e44a19815315c37/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/PositionerAtomAssembler.java#L34): Replace the synchronized class "StringBuffer" by an unsynchronized one such as "StringBuilder". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1149)
1. ![MAJOR][MAJOR] [ScanAtomAssembler.java#L93](https://github.com/eclipse/scanning/blob/1cc2b60843771f99282cc9bc1e44a19815315c37/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/ScanAtomAssembler.java#L93): Iterate over the "entrySet" instead of the "keySet". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2864)
1. ![MAJOR][MAJOR] [ScanAtomAssembler.java#L114](https://github.com/eclipse/scanning/blob/1cc2b60843771f99282cc9bc1e44a19815315c37/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/ScanAtomAssembler.java#L114): Call "deviceName.isPresent()" before accessing the value. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3655)
1. ![MAJOR][MAJOR] [ScanAtomAssembler.java#L122](https://github.com/eclipse/scanning/blob/1cc2b60843771f99282cc9bc1e44a19815315c37/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/ScanAtomAssembler.java#L122): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by Mark-Booth** [comment]
Look at the contents of the class it returns, it doesn't have any of the getter functions, so can't actually be used.

**Comment by gerring** [comment]
SonarQube analysis reported 28 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 10 minor
* ![INFO][INFO] 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [QueueBeanFactory.java#L153](https://github.com/eclipse/scanning/blob/16c9ef78f6460785204a4acf3e776c0b3507a06c/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/QueueBeanFactory.java#L153): Define a constant instead of duplicating this literal " found in registry." 4 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ServicesHolder.java#L28](https://github.com/eclipse/scanning/blob/16c9ef78f6460785204a4acf3e776c0b3507a06c/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/ServicesHolder.java#L28): Make the enclosing method "static" or remove this set. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2696)
1. ![CRITICAL][CRITICAL] [ServicesHolder.java#L29](https://github.com/eclipse/scanning/blob/16c9ef78f6460785204a4acf3e776c0b3507a06c/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/ServicesHolder.java#L29): Make the enclosing method "static" or remove this set. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2696)
1. ![CRITICAL][CRITICAL] [ServicesHolder.java#L33](https://github.com/eclipse/scanning/blob/16c9ef78f6460785204a4acf3e776c0b3507a06c/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/ServicesHolder.java#L33): Make the enclosing method "static" or remove this set. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2696)
1. ![CRITICAL][CRITICAL] [IBeanAssembler.java#L44](https://github.com/eclipse/scanning/blob/16c9ef78f6460785204a4acf3e776c0b3507a06c/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/IBeanAssembler.java#L44): Remove usage of generic wildcard type. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [IBeanAssembler.java#L55](https://github.com/eclipse/scanning/blob/16c9ef78f6460785204a4acf3e776c0b3507a06c/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/IBeanAssembler.java#L55): Remove usage of generic wildcard type. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [PositionerAtomAssembler.java#L34](https://github.com/eclipse/scanning/blob/16c9ef78f6460785204a4acf3e776c0b3507a06c/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/PositionerAtomAssembler.java#L34): Replace the synchronized class "StringBuffer" by an unsynchronized one such as "StringBuilder". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1149)
1. ![MAJOR][MAJOR] [ScanAtomAssembler.java#L93](https://github.com/eclipse/scanning/blob/16c9ef78f6460785204a4acf3e776c0b3507a06c/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/ScanAtomAssembler.java#L93): Iterate over the "entrySet" instead of the "keySet". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2864)
1. ![MAJOR][MAJOR] [ScanAtomAssembler.java#L114](https://github.com/eclipse/scanning/blob/16c9ef78f6460785204a4acf3e776c0b3507a06c/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/ScanAtomAssembler.java#L114): Call "deviceName.isPresent()" before accessing the value. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3655)
1. ![MAJOR][MAJOR] [ScanAtomAssembler.java#L122](https://github.com/eclipse/scanning/blob/16c9ef78f6460785204a4acf3e776c0b3507a06c/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/ScanAtomAssembler.java#L122): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by gerring** [comment]
SonarQube analysis reported 28 issues
* ![CRITICAL][CRITICAL] 6 critical
* ![MAJOR][MAJOR] 5 major
* ![MINOR][MINOR] 10 minor
* ![INFO][INFO] 7 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [QueueBeanFactory.java#L153](https://github.com/eclipse/scanning/blob/abbf18378417e3effb433bbf9d3429e4a9634f98/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/QueueBeanFactory.java#L153): Define a constant instead of duplicating this literal " found in registry." 4 times. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1192)
1. ![CRITICAL][CRITICAL] [ServicesHolder.java#L28](https://github.com/eclipse/scanning/blob/abbf18378417e3effb433bbf9d3429e4a9634f98/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/ServicesHolder.java#L28): Make the enclosing method "static" or remove this set. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2696)
1. ![CRITICAL][CRITICAL] [ServicesHolder.java#L29](https://github.com/eclipse/scanning/blob/abbf18378417e3effb433bbf9d3429e4a9634f98/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/ServicesHolder.java#L29): Make the enclosing method "static" or remove this set. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2696)
1. ![CRITICAL][CRITICAL] [ServicesHolder.java#L33](https://github.com/eclipse/scanning/blob/abbf18378417e3effb433bbf9d3429e4a9634f98/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/ServicesHolder.java#L33): Make the enclosing method "static" or remove this set. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2696)
1. ![CRITICAL][CRITICAL] [IBeanAssembler.java#L44](https://github.com/eclipse/scanning/blob/abbf18378417e3effb433bbf9d3429e4a9634f98/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/IBeanAssembler.java#L44): Remove usage of generic wildcard type. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1452)
1. ![CRITICAL][CRITICAL] [IBeanAssembler.java#L55](https://github.com/eclipse/scanning/blob/abbf18378417e3effb433bbf9d3429e4a9634f98/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/IBeanAssembler.java#L55): Remove usage of generic wildcard type. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1452)
1. ![MAJOR][MAJOR] [PositionerAtomAssembler.java#L34](https://github.com/eclipse/scanning/blob/abbf18378417e3effb433bbf9d3429e4a9634f98/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/PositionerAtomAssembler.java#L34): Replace the synchronized class "StringBuffer" by an unsynchronized one such as "StringBuilder". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1149)
1. ![MAJOR][MAJOR] [ScanAtomAssembler.java#L93](https://github.com/eclipse/scanning/blob/abbf18378417e3effb433bbf9d3429e4a9634f98/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/ScanAtomAssembler.java#L93): Iterate over the "entrySet" instead of the "keySet". [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS2864)
1. ![MAJOR][MAJOR] [ScanAtomAssembler.java#L114](https://github.com/eclipse/scanning/blob/abbf18378417e3effb433bbf9d3429e4a9634f98/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/ScanAtomAssembler.java#L114): Call "deviceName.isPresent()" before accessing the value. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS3655)
1. ![MAJOR][MAJOR] [ScanAtomAssembler.java#L122](https://github.com/eclipse/scanning/blob/abbf18378417e3effb433bbf9d3429e4a9634f98/org.eclipse.scanning.event.queuesspooler/src/org/eclipse/scanning/event/queuesspooler/beanassemblers/ScanAtomAssembler.java#L122): This block of commented-out lines of code should be removed. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3ACommentedOutCodeLine)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by jamesmudd** [comment]
It looks ok to me?
>>> from org.eclipse.scanning.event.queues.spooler import ServicesHolder as spooler         
>>> dir(spooler)
['__class__', '__copy__', '__deepcopy__', '__delattr__', '__doc__', '__ensure_finalizer__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__str__', '__subclasshook__', '__unicode__', 'class', 'equals', 'getClass', 'getCurrent', 'getRunnableDeviceService', 'getScannableDeviceService', 'hashCode', 'notify', 'notifyAll', 'setRunnableDeviceService', 'setScannableDeviceService', 'start', 'stop', 'toString', 'unsetRunnableDeviceService', 'unsetScannableDeviceService', 'wait']
>>> spooler.getCurrent()
org.eclipse.scanning.event.queues.spooler.ServicesHolder@2c4058b0
>>> spooler.getRunnableDeviceService()
org.eclipse.scanning.sequencer.RunnableDeviceServiceImpl@33ba55f
>>> spooler.getScannableDeviceService()
uk.ac.diamond.daq.scanning.ScannableDeviceConnectorService@162cc6f9
>>> 
The java class has 3 getters and the jython one does as well, and they all work?

**Comment by Mark-Booth** [comment]
I have now confirmed on the beamline that this isn't necessary.

I'm not sure why we were having problems before. I understand that an out of date launcher could have resulted in problems when running from Eclipse, but I can't understand why the exported product exhibited the problem which prompted this pull request.

**Pull request closed without merging**
