### PR TITLE
Added publisher as annotation data.

### PR DESCRIPTION
**Pull request by gerring**

### CODE REVIEW

**Comment by Mark-Booth** [comment]
That's odd, the pull request was still saying "The Travis CI build is in progress", but going to the travis page, it said it completed with a pass.

I have restarted the build again @gerring .

**Comment by gerring** [comment]
#115 is failing at the moment for the same test RemoteQueueControllerServiceTest. Could we @Ignore, merge everything back and then reenable the tests or should we wait until #115 passes and remove the @Ignore from this PR?

**Comment by mtwharmby** [comment]
I've just pushed up another change for the failing test to #115. Let's see if it works. If not, then just commit this PR as I don't see what else is causing the remote queue service test to fail.

**Comment by gerring** [comment]
@mpdickie and I are worried about a change we made to the object[] marshalling but it might not be the problem here.

**Comment by mtwharmby** [comment]
Build hung again, so I restarted it.

**Pull request merged**
