### PR TITLE
DAQ-974 Create service to configure UI elements specific to scannable

### PR DESCRIPTION
**Pull request by douglaswinter**

### CODE REVIEW

**Comment by Mark-Booth** [comment]
Travis build timed out, restarted.

**Comment by Mark-Booth** [comment]
Tried adding a gerrit test job using the merge commit used by travis (c20cc5f9dcb3f32564b8b8098938f2aa3188e9c7) but that failed with "error: Server does not allow request for unadvertised object c20cc5f9dcb3f32564b8b8098938f2aa3188e9c7" : http://jenkins.diamond.ac.uk:8080/job/GDA.master-junit.tests-gerrit/7642/console

Presumably this commit is only in travis' clone of the scanning repo.

Tried again to add a gerrit test job, this time using the last commit in the chain (c06c36fb910ba674e3d1816c89fe0c0bb4e94493) and this worked: http://jenkins.diamond.ac.uk:8080/job/GDA.master-junit.tests-gerrit/7643/

**Comment by douglaswinter** [comment]
Travis job keeps timing out...

**Comment by Mark-Booth** [comment]
@douglaswinter are you closing and re-opening to force a travis job restart?

If so, do you see a "Restart Build" option when you clicking on the Travis details link?

**Comment by douglaswinter** [comment]
@Mark-Booth That is indeed why I am closing/reopening requests. I have not seen that button, but I haven't been looking for it. I will let you know next time it happens.

**Comment by gerring** [comment]
I have just started an election for Douglas on scanning https://dev.eclipse.org/portal because I couldn't find a best beard contest

**Comment by Mark-Booth** [comment]
Thanks @gerring, I think it's much easier if people who are regularly committing become committers, rather than having to issue external pull requests.

@douglaswinter if you click on the Show all checks link, you should see the Details link in the travis section. As a committer though, I'm not sure what you see at the moment.

**Comment by douglaswinter** [comment]
@Mark-Booth I can go through to the Travis job details, but it does not give me the option to restart

**Comment by Mark-Booth** [comment]
Probably means it's tied to committer status then, which would make sense.

It would be good to confirm this once your committer status is approved.

**Pull request merged**
