### PR TITLE
I15_1-379

### PR DESCRIPTION
**Pull request by mtwharmby**
Makes QueueService more fault resistant by providing sensible default settings from queue-root and also makes bot queue-root and URI final. Also restructures init method of QueueService to only call things which depend on EventService.

Unit tests pass fine on my machine. **I have not tested whether this spins up OK with OSGi since plugin tests are broken in my development environment right now**

### CODE REVIEW

**Comment by mtwharmby** [comment]
Test fail was not mine, but I decided to modify something else.

**Comment by Mark-Booth** [comment]
This all looks good, if we get it merged in, I'll update my latest test version and configure its use so we can test tomorrow.

**Comment by mtwharmby** [comment]
@Mark-Booth can you merge this ASAP please as we need it on the beamline.

**Comment by Mark-Booth** [comment]
It doesn't need to be merged here in order for it to be on the beamline, and is indeed already in the gda-test.new version we tried on the beamline yesterday.

**Pull request merged**
